version: "3.8"

services:
  pack-n-jar:
    build: .
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_EMAIL_SERVICE_ID=service_72zi0oe
      - VITE_EMAIL_TEMPLATE_ID=template_s8tmhg8
      - VITE_EMAIL_PUBLIC_KEY=KzX2FdYujBD5LwJl4
    volumes:
      - .:/app
      - /app/node_modules
    command: ["pnpm", "run", "dev"]
