version: "3.8"

services:
  pack-n-jar:
    build: .
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_EMAIL_SERVICE_ID=${VITE_EMAIL_SERVICE_ID}
      - VITE_EMAIL_TEMPLATE_ID=${VITE_EMAIL_TEMPLATE_ID}
    volumes:
      - .:/app
      - /app/node_modules
    command: ["pnpm", "run", "dev", "--host"]
